CREATE TABLE tokens ( TOKEN_ID INTEGER PRIMARY KEY, TOKEN CHAR(6) NOT NULL, USED BOOLEAN DEFAULT 0 , BUDGET INTEGER DEFAULT 900);
CREATE TABLE usage ( USER CHAR(20) , USEDAT DATETIME NOT NULL , TOKEN CHAR(6) NOT NULL );
